service: ChangeDeliveryStatus
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-2
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource: ${ssm:/200OK/SNS/DeliveryStatus}

functions:
  startDelivery:
    handler: handler.start
    events:
      - httpApi:
          path: /start
          method: get
  endDelivery:
    handler: handler.end
    events:
      - httpApi:
          path: /end
          method: get
  environment:
    SNS_TOPIC: ${ssm:/200OK/SNS/DeliveryStatus}


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true