service: ChangeDeliveryStatus
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-2
  vpc:
    securityGroupIds:
      - ${ssm:/200OK/Security_Group/ID}
    subnetIds:
      - ${ssm:/200OK/subnet/ID}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource: ${ssm:/200OK/SNS/DeliveryStatus}
        - Effect: "Allow"
          Action:
            - "es:*"
          Resource: ["${ssm:/200OK/Opensearch/Arn}", "${ssm:/200OK/Opensearch/Arn}/*"]
  environment:
    SNS_TOPIC: ${ssm:/200OK/SNS/DeliveryStatus}
    OPENSEARCH_ENDPOINT: ${ssm:/200OK/Opensearch/Endpoint}

functions:
  startDelivery:
    handler: handler.start
    events:
      - httpApi:
          path: /start
          method: post
  endDelivery:
    handler: handler.end
    events:
      - httpApi:
          path: /end
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    fileName: requirements.txt