name: Deploy Websocket dev

on:
  push:
    branches:
      - develop
    paths: ['lambda/Websocket/**']

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # Use github defaut action to trigger action in this repo. Mandatory
      # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#using-the-checkout-action
      - uses: actions/checkout@v3
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Delete Files
        run: |
          rm -rf tf
          rm README.md
          rm .gitignore
      - name:
          env setting
        run: |
          export ENDPOINT_URL=$(aws lambda get-function-url-config --function-name websocket-app-dev-publish | jq .FunctionUrl -r)
          echo $ENDPOINT_URL
      - name:  
          serverless deploy
        run: |
          npm install -g serverless
          npm install -g serverless-dotenv-plugin
          serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cp -r lambda/Websocket/* ./
          npm install
          rm -rf lambda
          ls -all
          serverless deploy
