name: Deploy sendNotification dev

on:
  push:
    branches:
      - develop
    paths: ['lambda/sendNotification/**']

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      # Use github defaut action to trigger action in this repo. Mandatory
      # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#using-the-checkout-action
      - uses: actions/checkout@v3
      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Delete Files
        run: |
          rm -rf tf
          rm README.md
          rm .gitignore
      - name:  
          serverless deploy
        run: |
          npm install -g serverless
          serverless config credentials --provider aws --key ${{ secrets.aws_access_key_id }} --secret ${{ secrets.secrets.aws_secret_key_id }}
          cp -r lambda/sendNotification/* ./
          npm install
          rm -rf lambda
          ls -all
          serverless deploy





       
