name: run-script

on:
  push:
    branches:
      - develop

jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2


      - uses: actions/checkout@v1
      - name: script
        run: |
          chmod +x ./action.sh
          source action.sh
          echo 'ENDPOINT_URL<<EOF' >> $GITHUB_ENV
          aws lambda get-function-url-config --function-name websocket-app-dev-publish | jq .FunctionUrl -r >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

        shell: bash



