name: run-script
on: push


jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: script
        run: |
          chmod +x ./action.sh
          source action.sh
        shell: bash
