name: Deploy sendLocation dev

on:
  push:
    branches:
      - develop
    paths: ['lambda/sendLocation/**', '.github/workflows/ci_for_sendLocation.yaml']

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './lambda/sendLocation'
    strategy:
      matrix:
        python-version: [ '2.x', '3.x']
    steps:
    - uses: actions/checkout@v2
    - name: Use python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run: pwd
    - name: serverless deploy
      uses: serverless/github-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SERVERLESS_PATH: /home/runner/work/devops-01-final-TeamC-Scenario-02/devops-01-final-TeamC-Scenario-02/lambda/sendLocation
      with:
        args: deploy --config /home/runner/work/devops-01-final-TeamC-Scenario-02/devops-01-final-TeamC-Scenario-02/lambda/sendLocation/serverless.yml
    - run: echo $SERVERLESS_PATH
      # env:
      #   SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}